replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/gcp-gke-12345/application/myapp
  tag: hf-0001
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
